# Generated by Django 5.2.1 on 2025-06-10 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ders Başlığı')),
                ('meeting_url', models.URLField(max_length=500, verbose_name="Toplantı URL'i (Zoom Linki)")),
                ('start_time', models.DateTimeField(verbose_name='Ders Başlangıç Zamanı')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Ders Tamamlandı mı?')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors_lessons', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canlı Ders',
                'verbose_name_plural': 'Canlı Dersler',
                'ordering': ['start_time'],
            },
        ),
    ]
