# Generated by Django 5.2.1 on 2025-05-26 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0003_satinalim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='satinalim',
            old_name='satin_alma_tarihi',
            new_name='tarih',
        ),
        migrations.AlterUniqueTogether(
            name='satinalim',
            unique_together={('kullanici', 'egitim')},
        ),
    ]
