# Generated by Django 5.2.1 on 2025-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0004_rename_satin_alma_tarihi_satinalim_tarih_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitim',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='egitim_videolari/'),
        ),
        migrations.DeleteModel(
            name='SatinAlim',
        ),
    ]
