# Generated by Django 5.2.1 on 2025-05-27 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0005_egitim_video_delete_satinalim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('icerik', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('egitim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='egitimler.egitim')),
            ],
        ),
    ]
