# Generated by Django 5.2.1 on 2025-06-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta Adresi')),
                ('user_type', models.CharField(choices=[('egitmen', 'Eğitmen'), ('ogrenci', 'Öğrenci')], default='ogrenci', max_length=10, verbose_name='Kullanıcı Tipi')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Abone Olma Tarihi')),
            ],
            options={
                'verbose_name': 'Abone',
                'verbose_name_plural': 'Aboneler',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
