# Generated by Django 5.2.1 on 2025-05-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satinalim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satinalim',
            name='ilerleme_orani',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
