# Generated by Django 5.2.1 on 2025-06-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_book_mistaketype_readingassessment_readingmistake_and_more'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='textchapter',
            #name='book',
        #),
        migrations.RemoveField(
            model_name='readingmistake',
            name='mistake_type',
        ),
        migrations.RemoveField(
            model_name='readingassessment',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='readingassessment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='readingassessment',
            name='text_chapter',
        ),
        migrations.RemoveField(
            model_name='readingmistake',
            name='reading_assessment',
        ),
        migrations.AlterUniqueTogether(
            name='textchapter',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='MistakeType',
        ),
        migrations.DeleteModel(
            name='TextChapter',
        ),
        migrations.DeleteModel(
            name='ReadingAssessment',
        ),
        migrations.DeleteModel(
            name='ReadingMistake',
        ),
    ]
