# Generated by Django 5.2.1 on 2025-05-29 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EgzersizKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('basari', models.CharField(max_length=100)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KursIlerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('ilerleme', models.IntegerField(default=0)),
                ('durum', models.CharField(choices=[('devam ediyor', 'Devam Ediyor'), ('tamamlandı', 'Tamamlandı')], max_length=50)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OdevDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('teslim_durumu', models.CharField(choices=[('teslim edildi', 'Teslim Edildi'), ('bekleniyor', 'Bekleniyor')], max_length=100)),
                ('not_degeri', models.CharField(blank=True, max_length=20, null=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
