# Generated by Django 5.2.1 on 2025-05-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_egzersizkaydi_kursilerleme_odevdurumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorstudent',
            name='student_class',
            field=models.IntegerField(blank=True, null=True, verbose_name='Öğrenci Sınıfı'),
        ),
    ]
