# Generated by Django 5.2.1 on 2025-05-31 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
