# Generated by Django 5.2.1 on 2025-06-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_product_credit_order_assignedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_detail',
            field=models.TextField(blank=True, help_text='Bu ürünle ilgili detaylı içerik veya metin.', null=True, verbose_name='Ürün İçerik Detayı'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_file',
            field=models.FileField(blank=True, help_text='Bu ürünle ilişkilendirilecek PDF veya diğer dosya.', null=True, upload_to='product_content_files/', verbose_name='Ürün İçerik Dosyası (PDF, vb.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='content_link',
            field=models.URLField(blank=True, help_text='Bu ürünle ilişkilendirilecek harici bir link (video, web sayfası, vb.).', max_length=500, null=True, verbose_name='Ürün İçerik Linki'),
        ),
    ]
