# Generated by Django 5.2.1 on 2025-06-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0011_product_content_detail_product_content_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subscription_months',
            field=models.IntegerField(default=0, help_text='Bu ürün satın alındığında öğrencinin aboneliğine eklenecek ay sayısı.', verbose_name='Abonelik Süresi (Ay)'),
        ),
    ]
