# Generated by Django 5.2.1 on 2025-06-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0012_product_subscription_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bu ürünün indirimsiz veya eski fiyatı. Boş bırakılırsa gösterilmez.', max_digits=10, null=True, verbose_name='Orijinal Fiyat'),
        ),
    ]
