# Generated by Django 5.2.1 on 2025-06-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0014_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_used_for_assignment',
            field=models.BooleanField(default=False, verbose_name='Atama İçin Kullanıldı Mı?'),
        ),
    ]
