# Generated by Django 5.2.1 on 2025-06-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_order_is_used_for_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_used_for_assignment',
        ),
    ]
