# Generated by Django 5.2.1 on 2025-05-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='assigned_manually',
            field=models.BooleanField(default=False),
        ),
    ]
