# Generated by Django 5.2.1 on 2025-06-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text="Makale URL'si için benzersiz kısa isim", max_length=200, unique=True)),
                ('ozet', models.TextField(help_text='Ana sayfada görünecek kısa özet')),
                ('icerik', models.TextField(help_text='Makalenin tam içeriği (HTML/Markdown olabilir)')),
                ('yayinlanma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gorsel', models.ImageField(blank=True, help_text='Makalenin görseli/kapak resmi', null=True, upload_to='makale_gorselleri/')),
            ],
            options={
                'ordering': ['-yayinlanma_tarihi'],
            },
        ),
    ]
