# Generated by Django 5.2.1 on 2025-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='ozet',
            field=models.TextField(help_text='Makale listeleme sayfasında görünecek kısa özet'),
        ),
    ]
