# Generated by Django 5.2.4 on 2025-08-05 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Kitap için benzersiz kısa isim (URL'de kullanılacak)", max_length=100, unique=True)),
                ('baslik', models.CharField(max_length=200)),
                ('yazar', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('fiyat_kurus', models.IntegerField(help_text='Fiyat (kuruş cinsinden)')),
                ('icerik_url', models.URLField(blank=True, help_text="Kitabın dijital içeriğinin URL'si (PDF, e-kitap vb.)", null=True)),
                ('resim', models.ImageField(blank=True, help_text='Kitabın kapak resmi', null=True, upload_to='kitap_resimleri/')),
            ],
        ),
        migrations.CreateModel(
            name='Oyun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Oyun için benzersiz kısa isim (URL'de kullanılacak)", max_length=100, unique=True)),
                ('baslik', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=100)),
                ('yapimci', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('fiyat_kurus', models.IntegerField(help_text='Fiyat (kuruş cinsinden)')),
                ('icerik_url', models.URLField(blank=True, help_text='Oyunun indirme veya erişim linki', null=True)),
                ('resim', models.ImageField(blank=True, help_text='Oyunun görseli/kapak resmi', null=True, upload_to='oyun_resimleri/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('instructor', 'Eğitmen Yazılımı'), ('student', 'Öğrenci Yazılımı')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_cents', models.IntegerField(help_text='Fiyat (kuruş cinsinden)')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_manually', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KitapSatınAlım',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('odendi', models.BooleanField(default=False)),
                ('satinalma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kitap', 'odendi')},
            },
        ),
        migrations.CreateModel(
            name='OyunSatınAlım',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('odendi', models.BooleanField(default=False)),
                ('satinalma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('oyun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.oyun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'oyun', 'odendi')},
            },
        ),
    ]
