# Generated by Django 5.2.1 on 2025-06-01 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchase_assigned_manually'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Kitap için benzersiz kısa isim (URL'de kullanılacak)", max_length=100, unique=True)),
                ('baslik', models.CharField(max_length=200)),
                ('yazar', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('fiyat_kurus', models.IntegerField(help_text='Fiyat (kuruş cinsinden)')),
                ('icerik_url', models.URLField(blank=True, help_text="Kitabın dijital içeriğinin URL'si (PDF, e-kitap vb.)", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oyun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Oyun için benzersiz kısa isim (URL'de kullanılacak)", max_length=100, unique=True)),
                ('baslik', models.CharField(max_length=200)),
                ('platform', models.CharField(blank=True, help_text='Oynanabileceği platform (PC, PlayStation vb.)', max_length=100)),
                ('yapimci', models.CharField(blank=True, max_length=100)),
                ('aciklama', models.TextField()),
                ('fiyat_kurus', models.IntegerField(help_text='Fiyat (kuruş cinsinden)')),
                ('indirme_url', models.URLField(blank=True, help_text="Oyunun indirme/erişim URL'si", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitapSatınAlım',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('odendi', models.BooleanField(default=False)),
                ('satinalma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kitap', 'odendi')},
            },
        ),
        migrations.CreateModel(
            name='OyunSatınAlım',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=200)),
                ('odendi', models.BooleanField(default=False)),
                ('satinalma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('oyun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.oyun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'oyun', 'odendi')},
            },
        ),
    ]
