# Generated by Django 5.2.1 on 2025-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_kitap_oyun_kitapsatınalım_oyunsatınalım'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='resim',
            field=models.ImageField(blank=True, help_text='Kitabın kapak resmi', null=True, upload_to='kitap_resimleri/'),
        ),
    ]
