# Generated by Django 5.2.1 on 2025-06-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_kitap_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oyun',
            name='indirme_url',
        ),
        migrations.AddField(
            model_name='oyun',
            name='icerik_url',
            field=models.URLField(blank=True, help_text='Oyunun indirme veya erişim linki', null=True),
        ),
        migrations.AddField(
            model_name='oyun',
            name='resim',
            field=models.ImageField(blank=True, help_text='Oyunun görseli/kapak resmi', null=True, upload_to='oyun_resimleri/'),
        ),
        migrations.AlterField(
            model_name='oyun',
            name='platform',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='oyun',
            name='yapimci',
            field=models.CharField(max_length=100),
        ),
    ]
