# Generated by Django 5.2.4 on 2025-08-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egitim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('seviye', models.CharField(choices=[('Baslangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri', 'İleri')], default='Baslangic', max_length=20)),
                ('sure', models.PositiveIntegerField(default=0, help_text='Ders süresi (dakika cinsinden)')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='egitim_gorselleri/')),
                ('video', models.FileField(blank=True, null=True, upload_to='egitim_videolari/')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('icerik', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('egitim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='egitimler.egitim')),
            ],
        ),
    ]
