# Generated by Django 5.2.1 on 2025-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egitim',
            name='fiyat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='egitim',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='egitim_gorselleri/'),
        ),
        migrations.AddField(
            model_name='egitim',
            name='seviye',
            field=models.CharField(choices=[('Baslangic', 'Başlangıç'), ('Orta', 'Orta'), ('Ileri', 'İleri')], default='Baslangic', max_length=20),
        ),
        migrations.AddField(
            model_name='egitim',
            name='sure',
            field=models.PositiveIntegerField(default=0, help_text='Ders süresi (dakika cinsinden)'),
        ),
    ]
