# Generated by Django 5.2.1 on 2025-05-26 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0002_egitim_fiyat_egitim_gorsel_egitim_seviye_egitim_sure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatinAlim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satin_alma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('egitim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egitimler.egitim')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
