# Generated by Django 5.2.1 on 2025-06-09 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(help_text="URL için benzersiz kısa isim, örn: 'dikkat-odaklanma'", unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon_class', models.CharField(blank=True, help_text="FontAwesome ikon sınıfı, örn: 'fas fa-brain'", max_length=50, verbose_name='İkon Sınıfı')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sıralama için kullanılır, küçük olan önce gelir.')),
            ],
            options={
                'verbose_name': 'Egzersiz Kategorisi',
                'verbose_name_plural': 'Egzersiz Kategorileri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Oyun Adı')),
                ('slug', models.SlugField(help_text="URL için benzersiz kısa isim, örn: 'eslestirme-kartlari'", unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Oyun Açıklaması')),
                ('template_name', models.CharField(help_text="Bu oyunun oynanacağı HTML şablonunun yolu, örn: 'exercises/games/memory_pairs.html'", max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='exercises.exercisecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Egzersiz Oyunu',
                'verbose_name_plural': 'Egzersiz Oyunları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Puan')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Doğru Sayısı')),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name='Yanlış Sayısı')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Oyunun tamamlanma süresi (saniye)', verbose_name='Süre (saniye)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Oynanma Zamanı')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exercises.exercisegame', verbose_name='Oyun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Oyun Denemesi',
                'verbose_name_plural': 'Oyun Denemeleri',
                'ordering': ['-timestamp'],
            },
        ),
    ]
