# Generated by Django 5.2.1 on 2025-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructorstudent_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorstudent',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Öğrencinin eğitmenle olan abonelik süresi (ay cinsinden).', null=True, verbose_name='Abonelik Süresi (Ay)'),
        ),
        migrations.AddField(
            model_name='instructorstudent',
            name='end_date',
            field=models.DateField(blank=True, help_text='Öğrencinin aboneliğinin biteceği tarih.', null=True, verbose_name='Abonelik Bitiş Tarihi'),
        ),
    ]
