# Generated by Django 5.2.1 on 2025-05-31 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_remove_profile_first_name_remove_profile_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kurs Adı')),
                ('total_days', models.IntegerField(default=0, verbose_name='Toplam Gün Sayısı')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atanma Tarihi')),
                ('completed_days', models.IntegerField(default=0, verbose_name='Bitirilen Gün Sayısı')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme Tarihi')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_assigned_courses', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course', verbose_name='Atanan Kurs')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
