# Generated by Django 5.2.1 on 2025-05-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_course_assignedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exercises_per_day',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
