# Generated by Django 5.2.1 on 2025-06-04 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_course_exercises_per_day_alter_course_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Ürün Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Kredi Miktarı')),
                ('instructor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen')),
            ],
            options={
                'verbose_name': 'Kredi',
                'verbose_name_plural': 'Krediler',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi Mi?')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='AssignedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Atama Tarihi')),
                ('is_used', models.BooleanField(default=False, verbose_name='Kullanıldı Mı?')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_products_by_instructor', to=settings.AUTH_USER_MODEL, verbose_name='Atayan Eğitmen')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_products_to_student', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Öğrenci')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.product', verbose_name='Atanan Ürün')),
            ],
            options={
                'verbose_name': 'Atanan Ürün',
                'verbose_name_plural': 'Atanan Ürünler',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
