# Generated by Django 5.2.1 on 2025-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0017_order_is_used_for_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='Eğitmen Mi?'),
        ),
    ]
