# Generated by Django 5.2.1 on 2025-06-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0018_remove_order_quantity_profile_is_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Adet'),
        ),
    ]
