# Generated by Django 5.2.1 on 2025-06-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0020_book_mistaketype_livelesson_readingassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelesson',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Tamamlandı Mı?'),
        ),
        migrations.AddField(
            model_name='mistaketype',
            name='color',
            field=models.CharField(default='#007bff', help_text='Hata tipi için HEX renk kodu (örn: #FF0000)', max_length=7, verbose_name='Renk Kodu'),
        ),
    ]
